---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'todo'
Resources:

  RestAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: {{api_name}}

  PersonsGreeting:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      Name: PersonsGreeting
      RestApiId:
        Ref: RestAPI
      Schema:
        "$schema": http://json-schema.org/draft-04/schema#
        title: PersonsGreeting
        type: object
        additionalProperties: false
        properties:
          greeting:
            type: string
        required:
        - greeting

  Greet:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: RestAPI
      ParentId:
        Fn::GetAtt:
        - RestAPI
        - RootResourceId
      PathPart: greet

  GreetPerson:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: RestAPI
      ParentId:
        Ref: Greet
      PathPart: "{name}"

  GetGreetPerson:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: "GET"
      AuthorizationType: "NONE"
      ResourceId:
        Ref: GreetPerson
      RestApiId:
        Ref: RestAPI
      Integration:
        IntegrationHttpMethod: "POST"
        Type: AWS_PROXY
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::ImportValue: {{api_name}}TestLambdaArn
            - "/invocations"
      RequestParameters:
        method.request.path.name: true
      MethodResponses:
      - ResponseModels:
          application/json:
            Ref: PersonsGreeting
        ResponseParameters:
          method.response.header.Link: true
        StatusCode: 200

  GreetingsPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::ImportValue: {{api_name}}TestLambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: RestAPI
          - "/*/*/*"
